kind = "web"
previewPath = "/"
title = "EduMate"
version = "1.0.0"
id = "artifacts/edumate"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18171

[services.development]
run = "pnpm --filter @workspace/edumate run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/edumate", "run", "build" ]
publicDir = "artifacts/edumate/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18171"
BASE_PATH = "/"
